params:
  num_image_pairs: 25
  num_matches_per_image_pair: 100

networks:
  caterpillar_3:
    path_to_network_params: code/data_volume/pdc/trained_models/tutorials/caterpillar_3/003500.pth
  linemod_01_4:
    path_to_network_params: code/data_volume/pdc/trained_models/tutorials/linemod_01_4/003500.pth

dataset: [] # which dataset to use, not used for now

output_dir: code/data_volume/pdc/analysis
